temp

diff --git a/.github/workflows/final2.yml b/.github/workflows/final2.yml
--- a/.github/workflows/final2.yml
+++ b/.github/workflows/final2.yml
@@ -10,6 +10,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Make fail if the previous workflow was failed
+        if: ${{ github.event.workflow_run.conclusion != 'success' }}
+        run: |
+          echo '::error::Previous workflow was failed'
+          exit 1
       # Checks out a copy of your repository on the ubuntu-latest machine
       - name: Checkout code
         uses: actions/checkout@v2
